### ISSUE TITLE
Setting default sidebar state

### ISSUE THREAD

**Issue by MOFTAD** [Quicksaver/OmniSidebar#102]
I'm not sure if I've just missed it in the options, but I've checked a few times now and I don't believe there is a way to set your default sidebar state upon Firefox startup (e.g. open or closed). As of now, I find that my main sidebar is always open when I start, and I'd rather have it closed by default. Otherwise, the extension has been perfect (converted from AiOS after using it for years) - thank you for your work.

**Comment by Quicksaver** [comment]
I'm glad you like the add-on! :)

The sidebar should remember its state from the last Firefox session. For instance, if you close Firefox with the sidebar open, the next time you start Firefox it will also be open. Same thing if you restart Firefox with the sidebar closed, it will also be closed when it starts up again.

There is however a bug that prevents this from working properly sometimes, I wonder if that's what you're experiencing. This bug should already be fixed in version 1.6.6 which is already in the queue to be reviewed, so if the current version doesn't work correctly for you on this matter, please try it (https://addons.mozilla.org/firefox/addon/omnisidebar/). Let me know how it goes.

**Comment by Quicksaver** [comment]
Edit above: corrected the link.

**Comment by MOFTAD** [comment]
Thank you! The update works perfectly! Now it truly is perfect :)

**Comment by Quicksaver** [comment]
I'm glad to hear it. :)
