### ISSUE TITLE
Connection between Firefox skin and Omnisidebar

### ISSUE THREAD

**Issue by bibihh** [Quicksaver/OmniSidebar#104]
It's there any way in which the OmniSidebar can use the currently loaded skin in Firefox

When I apply different skin in Firefox, that's not changing the skin on the sidebars. The only option, which I see from the Omnisidebar options is to apply glass style.

**Comment by Quicksaver** [comment]
If you mean lightweight themes (where only the background of the toolbars changes), then that's not possible, because those background images aren't tall enough to cover the whole height of the sidebar.

If you mean full themes, then you'll have to contact the theme developers and ask them to add support for whatever sidebar panels you use (bookmarks, history, add-ons, etc. each one will have to be styled individually).
