### ISSUE TITLE
[help] my sidebar addon doesn't work well with OmniSidebar

### ISSUE THREAD

**Issue by nobodxbodon** [Quicksaver/OmniSidebar#111]
Dear Developer,

this is how I created sidebar in my addon:
https://github.com/nobodxbodon/HistoryInThreads/blob/master/lib/main.js

My user likes my addon but reported the incompatibility issue:
https://addons.mozilla.org/en-US/firefox/addon/history-in-threads/reviews/772575/

I haven't updated my knowledge about sidebar for a while so very likely I missed something very obvious.

Any suggestion is more than welcome!

Thanks a lot.

Best,
Xuan.

**Comment by Quicksaver** [comment]
That's because you register your sidebar using the sdk, and the sdk creates the sidebar in the worst possible way I have ever seen...

This is the first time I'm looking at an sdk sidebar. I'll try to add support for this, but I can't make any promises though, this part of the sdk really is absolutely ugly.
