### ISSUE TITLE
sidebar open when FF loads

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/OmniSidebar#118]
linux mint
ff 44.0.2
omni 1.6.11

if the option to 'Keep the panel loaded when the sidebar closes' is enabled, FF starts with the sidebar open even when it is closed on exit

**Comment by Quicksaver** [comment]
Seems to be working as expected for me. Does this happen with all sidebars or only one in specific? And does this happen if you disable all your other add-ons except for OSB?

**Comment by atomGit** [comment]
hi Quicksaver

let me troubleshoot further and i'll get back to you - might be a day or two

**Comment by atomGit** [comment]
i spent a good bit of time trying to troubleshoot this and i wasn't able to find the cause

9 time out of 10 is't a setting in my user.js and so i started going through that and - problem solved - then i'd do another restart without changing anything and the problem was back

then i started moving files and folders out of the profile, starting each time with no prefs and no user js file - thought i had it narrowed down, ut after another restart in the same exact condition, the problem was back

i ended up deleting everything except /extensions/osb@quicksaver.xpi and the problem still existed, then after another restart with only the aforementioned objects in my profile, it was solved

it's an annoying problem to have the sidebar auto-open on each load, regardless of its state on exit, but i can't figure out the cause - all i can say at this point is that maybe it's not a conflict with anything else as far as prefs and extensions, but maybe something to do with a combination of my particular machine and FF, your ext, etc. ... who knows

**Comment by Quicksaver** [comment]
I think it's safe to say the problem is with the add-on. I did see this happen once on my dev profile, but it only persisted for three or four Firefox restarts, and only with the Add-ons Sidebar; other sidebars would remember fine. And now I can't reproduce it anymore otherwise that would be just too easy of course. ;)

Can you tell if it happens with the native sidebars (bookmarks, history) or only with ones included in OSB (addons, download, console...)?

**Comment by atomGit** [comment]
for me the sidebar state is not remembered if it is closed on exit for the following...

bookmarks
history
downloads
add-ons
ScrapBookX

the only sidebar for which the state is remembered is the console

again, if i disable the option to 'keep the panel loaded ...', then the problem is solved for all sidebar panels

hope that helps :)

**Comment by Quicksaver** [comment]
I've been trying to figure out a way to reproduce this, but so far I've come up with nothing... Just by looking at the code, nothing is really jumping up as "possible culprits" either.

Can you tell if this happens / doesn't happen when you start Firefox with a new session or are resuming the previous session?

**Comment by atomGit** [comment]
happens either way

wish i could help you more - if you think of anything i can do, let me know

**Comment by Quicksaver** [comment]
That's somewhat helpful actually. The sidebar opened and closed state is remembered in two different ways, one of which through a saved preference (which acts like a flag to know if it was open or not). You can check it, after you close the browser, by going to your profile folder and opening the prefs.js file in a text editor, then look for ```extensions.omnisidebar.lastStateMain``` and checking its ```closed``` value.

More than likely this is what's happening: if you close the sidebar before exiting the browser, then the closed value in that preference will be ```true```. And if the sidebar still opens then, it's likely that it's Firefox itself opening the sidebar during startup, because it saves its state in a totally different place. I already try to override this with the add-on, but it's hard since the add-on starts a little delayed from the actual browser startup, so I'm almost sure that what's happening is that the add-on isn't catching Firefox internals in time to stop the sidebar from opening.

I need to investigate how to do this in a better way...

**Comment by Quicksaver** [comment]
If I'm correct about what's happening, [beta version 1.6.13b1](https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.13b1) should fix it. Please try it out and let me know how it works.

**Comment by atomGit** [comment]
looks like you were right - problem solved :)

thanks a ton!

**Comment by Quicksaver** [comment]
I'm glad to hear it. :)
