### ISSUE TITLE
"Logic Confict" with Public Fox

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/OmniSidebar#123]
Public Fox is used to "lock up" Firefox but with OmniSidebar Public Fox becomes meaningless.
You first install OmniSidebar and choose always to activate it and display add-ons as default.
Then install Public Fox to "lock up" Firefox.
Now anyone else who doesn't have the password to Public Fox should have been able to master your Firefox. BUT:
Find out OmniSidebar and then disable Public Fox and restart.
The restriction from Public Fox is now easily got rid of.
My suggestion is to force inactivate OmniSidebar when Public Fox has a password.

**Comment by Quicksaver** [comment]
Because you have to input a password, this has to be done from within Public Fox, as it's just not safe (if even possible) to somehow have it enter a password from my side. And to simply disable it, you can just do that yourself if you can install add-ons after all.

I really don't suggest using it anyway, it hasn't been updated for over a year. I can enter about:preferences without a problem when I'm not supposed to, and that's just the first thing I thought to test. Plus, the author gives a simple trick to disable it as well in the developer's comments, anyone that can run Firefox in any computer can also run it in safe-mode.
