### ISSUE TITLE
Download panel bug on Firefox 47

### ISSUE THREAD

**Issue by bastien30** [Quicksaver/OmniSidebar#125]
Hi,

First, thank you for this great add-on !

It seems there is a bug on the downloads panel (the one with the top button to clean download list) on Firefox 47.
When there is no download on the list, the button to clean download list is black and clickable, but when there is one or more downloads, the button is greyed.
After switching from downloads panel to another and switching back, the button is black and it can be used.

I think this has to be the reverse.

This appear only since Firefox 47.

Thanks in advance.

**Comment by bastien30** [comment]
Any news ?

The problem appears on Windows and Linux with a clean profile.

**Comment by bastien30** [comment]
The problem is still there with Firefox 48...

Am I the only one using this functionnality ??
A month and a half without even an answer...

**Comment by Quicksaver** [comment]
I'm sorry about the lack of updates. I still need to check it out, as it's entirely possible they changed something that made it not start up properly the first time it opens. I'll try to look into it soon and I'll let you know. I'm so sorry for not having been able to give you a proper response sooner, as I haven't even had a chance to test it out properly myself since you reported the issue originally.

**Comment by bastien30** [comment]
It seems that the problem no longer happen since Firefox 49, I presume it was probably related to Firefox and not OmniSidebar.

Sorry to have bothered you, I close the ticket.
