### ISSUE TITLE
Mini Panel With Tab Mix Plus

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/OmniSidebar#128]
STR:
1.install TMP and enable tab restore feature
2.install OSB, enable the mini panel feature and place TMP's Closed Tabs button (or other button with a drop down menu) on OSB main sidebar, aka next to the title. Try to place more on this step, you can also place all buttons from TMP.
3.right click the browser margin to open the mini panel
4.try to access the drop down menu from TMP's Closed Tabs button
Actual Results:
1.drop down menu from TMP's Closed Tabs button can not be accessed
2.now go back to the OSB main sidebar, other buttons you placed are all gone, including those from TMP (reappear after re-enable OSB from Firefox addons manager).
NOTE: any issue with buttons from other addons not found yet.

**Comment by Quicksaver** [comment]
Thank you for the detailed steps, I'll be sure to check it out.

**Comment by Quicksaver** [comment]
This should be fixed in [beta version 1.6.14b1](https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.14b1). Please give it a try and let me know how it works for you.

Note that the dropdown popups still won't open while the button is in the mini panel, but there's nothing I can do about that, Firefox really doesn't like it when a popup tries to anchor itself to a panel. But at least the buttons will return back to the toolbars now once it closes, so everything else should keep working as expected.

**Comment by EMLVIRUS** [comment]
Everything is now how you described, thanks.
