### ISSUE TITLE
Open OmniSidbar by mouse hover?

### ISSUE THREAD

**Issue by Tommm-24** [Quicksaver/OmniSidebar#146]
"Durch Klick auf den Rand des Browser-Fensters kann die Sidebar geöffnet und geschlossen werden. Der Rand leuchtet auf, falls diese Funktion aktiviert ist, sodass Sie wissen, wann Sie klicken können."
Das funktioniert auch einwandfrei. Ich fände es aber gut, wenn das nicht nur durch Mausklick so funktionieren würde, sonder auch durch mouse hover z.B. nach einer gewissen Anzahl von ms.
Wäre das möglich?

**Comment by EMLVIRUS** [comment]
Are these the translation?
English
"By clicking on the edge of the browser window the sidebar can be opened and closed. The edge lights up if this function is activated, so that you know when you can click."
The works also fine. I'd it but good if that would work not only by mouse click, but also by mouse hover for example after a certain number of ms.
Would that be possible?
If so
Actually I think such feature exists already.

**Comment by Tommm-24** [comment]
Hi Quicksaver,

maybe I just don't understand how to use or activate this feature. The 
Sidebar opens on my firefox only by clicking on the blue edge, not by 
mouse hover over blue edge. If I uncheck "the open by click" in options 
the sidebar does not open at all


Am 04.01.2017 um 13:14 schrieb EMLVIRUS:

**Comment by EMLVIRUS** [comment]
Actually, I'm not the owner. Sorry :-)
Maybe try to tick them both?
![20170104_203649](https://cloud.githubusercontent.com/assets/16912240/21642517/a996c77a-d2bd-11e6-8e56-9cff1daf036e.jpg)

**Comment by Quicksaver** [comment]
Yep that only works with the sidebar undocked.

**Comment by Tommm-24** [comment]
Yes, this works fine, I did undock the bar from browser window before.

Thanks and best regards


Am 04.01.2017 um 13:38 schrieb EMLVIRUS:
