### ISSUE TITLE
2 clicks necessary to open sidebar after customize

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/OmniSidebar#73]
after you open about:customizing and close it, 2 clicks are necessary on the sidebar switch to open it

**Comment by Quicksaver** [comment]
I'm sorry for the delay on this. I can't reproduce this at all. Could you give the latest beta version 1.5.1b2 a try and see if it still happens there? You can find it at the top of https://addons.mozilla.org/firefox/addon/omnisidebar/versions/

**Comment by atomGit** [comment]
hi Quicksaver :)
bug is still present in the beta
try this:
restart FF
menu panel > customize > exit customizer
then click the sidebar switch to see if it opens - for me it did
then repeat the process - now it doesn't open until the second click

really no big deal though - i mentioned it primarily in the even it might be a symptom of another problem

**Comment by Quicksaver** [comment]
It works fine for me. I imagine you're in Win7 like you mentioned in the other issue, and have since updated to FF35. Does this also happen if you disable all your other add-ons? How do you have the sidebar configured (docked/undocked/autohide/margin switch enabled/left or right side)?

It's very weird that the sidebar isn't opening immediately with the first click. I agree that it's not that big of a deal, but I'd like to try to fix it if I can. :)

**Comment by atomGit** [comment]
it doesn't do it with a clean profile - it is something in my preferences, but i gave up trying to find it because i couldn't reproduce it reliably 
sorry for the hassle - i should have tested with a clean profile in the beginning

**Comment by Quicksaver** [comment]
If you do find out what causes this exactly, please re-open this issue (or open a new one).
