### ISSUE TITLE
serious icon issues

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/OmniSidebar#98]
OSB 1.6 / 1.6.2
FF 40.0.2
WIN 7

having some serious icon issues that i believe i have narrowed down to a combination of OSB 1.6/1.6.2 and FF 40.0.2

although not all these scree-caps were done with a fresh profile, these problems were present with a completely empty profile

in this capture, look at the icons circled in blue - in some cases they are actually 2 overlapping icons and in other cases they are the wrong icon and other times they change when clicked on, or clicked off of
http://s6.postimg.org/o3jgeayap/screenshot_192.png

in this capture, look at the scroll bar - it appears to be overlaid with a firefox icon...
http://s6.postimg.org/o4xzlgpi9/screenshot_193.png

in this capture, look at the menu icons...
http://s6.postimg.org/low67m7fl/screenshot_194.png

these issues are not present with FF 39 and OSB 1.6

**Comment by Quicksaver** [comment]
My guess is, something was changed in Firefox 40 rendering which causes glitches like these. I'll try to track it down and confirm whether this is really caused by OSB or not. I'm going to take a wild guess that this actually isn't caused by OSB, other than it just making it more obvious like in the case of the add-ons sidebar (OSB goes nowhere near the webpage or its scrollbar, and the menu looks fine to me).

Just to make sure, when you say "completely empty profile", do you mean with or without OSB? And are you absolutely sure all of these issues occur in an empty profile with only OSB, and that they do not occur without OSB?

I'm sorry to sound so "stubborn", but that really is a very weird problem. My first guess would have been that whatever customizations you have for the add-ons sidebar (which you seem to have a few judging from that screenshot) could have easily caused the "weird icons" issue. But then there's also a weird icon in the sidebar toolbar...

**Comment by atomGit** [comment]
there were apparently rendering changes in 40 - i noticed major issues if i disable hardware accel

and yes, i tested with a _completely_ empty profile, other than OSB of course - without OSB, i could not reproduce any of this weirdness with any profile configuration 

also i tested with OSB on an empty profile with all default OSB settings

i'm going to run some more tests and report back if i find anything new

**Comment by Quicksaver** [comment]
Does any of it happen when the sidebar is closed or docked, or only if the add-ons sidebar is open? Have you noticed anything in any of the other sidebars, like bookmarks?

**Comment by atomGit** [comment]
there's no problem with bookmarks in OSB - the only panel that was borked was the add-on panel

there were other problems outside of OSB as you saw in the screen-caps

i ran a couple more tests last night and didn't come up with anything new, other than i absolutely cannot disable hardware accel with FF 40, else there is allot of rendering issues where much of the browser is apparently never re-painted and things are the wrong size, missing text on tabs, etc.

one of my problems is that i have a notebook and because its a notebook i cannot use ANY other driver than the ones provided by the vendor, so my display driver is quite old - Nvidia 1.10.62.40 - whether that may be causing problems here, i don't know

**Comment by Quicksaver** [comment]
> there's no problem with bookmarks in OSB - the only panel that was borked was the add-on panel

I meant if the problems outside of the addons sidebar, like the weird firefox logo over the scrollbar, appear only when the addons sidebar is open or if any other sidebar is open? Or does it also appear when the sidebar is closed? Or only un/docked? Etc..

> one of my problems is that i have a notebook and because its a notebook i cannot use ANY other driver than the ones provided by the vendor

More often than not this isn't true. For instance, any notebook with an Nvidia card should be able to update to the latest driver available to it from Nvidia's support site, regardless of what the notebook's own manufacturer website lists as the "latest" driver. What is your gfx card if you don't mind me asking?

**Comment by atomGit** [comment]
i didn't try undocking it, but the problem with the icons for the menu button menu exists when the add-ons bar is closed - you want me to run more tests?

i have a GTX 460M in a Clevo/Sager notebook - i have installed a few different versions of OEM drivers from the manufacturer for newer notebooks with the same card or a similar card, as well as a crap-load of versions from Nvidia and in every single instance the card seems to run hotter (i notice a change in fan speed) and i blue-screen at some point - may take minutes or months

Clevo/Sager are high quality machines, but i will never buy another notebook because of this - i'm going back to building my own

**Comment by Quicksaver** [comment]
I was just wondering if the undocked CSS scripts were somehow causing this, but if your sidebar is docked then I guess not. And if this happens with the sidebar closed even, that's even stranger.

> the problem with the icons for the menu button menu exists when the add-ons bar is closed

I still don't understand what the problem is with your menu. The screenshot where you mentioned this seems fine to me. Maybe I'm missing something?...

> i have installed a few different versions of OEM drivers from the manufacturer for newer notebooks with the same card or a similar card, as well as a crap-load of versions from Nvidia and in every single instance the card seems to run hotter and I blue-screen

That's very unfortunate, as you said yourself, the driver you're using is very old now. So it could well cause these issues (or at least be a part of the cause), considering you have hardware acceleration enabled.

I wonder if I can convince you to try Nvidia's most recent driver (355.60 - http://www.geforce.com/drivers/results/89121) for only a little bit, to see if it helps with the issue. At the least we could rule that out. :)

**Comment by atomGit** [comment]
FF 40.0.2 - h/w accel enabled (still can't disable if i wanted to - lots of corruption)
Nvidia 355.60 - no optional components installed

the icon and scroll-bar corruption issues seem to be gone

my CPU and MB temps are a tad bit higher (1-2C), but GPU temp is down slightly (~2C)

so far system seems stable, but only [allot] of time will tell - it would be VERY F'N NICE if this driver actually works

sorry it took this long to figure out it was (apparently) the display driver - i'll let you close this since i don;t know if you'll see this comment if i close it ???

**Comment by Quicksaver** [comment]
Notifications of new comments work on closed issues as well. ;)

Still, I'd like to leave this open for a few days at least, to give you some time to see how the new driver works for you, and if the issue is completely gone or if it just "happens less".

**Comment by atomGit** [comment]
roger that
thanks for prompting to try the new driver ... fingers crossed!

**Comment by Quicksaver** [comment]
I take it from your silence that everything has been working well. :) Feel free to reopen the issue if it ever happens again for any reason.
